preUpgradeChecker:
  jobEnabled: false
defaultSettings:
  defaultDataPath: /mnt/longhorn
  createDefaultDiskLabeledNodes: false
  defaultReplicaCount: 2
csi:
  kubeletRootDir: /var/snap/microk8s/common/var/lib/kubelet