apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: RENOVATE_TOKEN
              value: $azurekv-secrets:github-personal-access-token-argocd
            envFrom:
            - configMapRef:
                name: env-vars
            image: renovate/renovate:38.72.1
            name: renovate
            volumeMounts:
            - mountPath: /opt/renovate/
              name: config-volume
            - mountPath: /tmp/renovate/
              name: work-volume
          restartPolicy: Never
          volumes:
          - configMap:
              name: config
            name: config-volume
          - emptyDir: {}
            name: work-volume
  schedule: '@hourly'
