apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keel-secrets
  namespace: keel
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv-secret-store
  target:
    name: keel-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        BASIC_AUTH_PASSWORD: "{{ index . \"keel-password\" | trim }}"
        DISCORD_WEBHOOK_URL: "{{ index . \"discord-webhook-url\" | trim }}"
  data:
  - secretKey: keel-password
    remoteRef:
      key: keel-password
  - secretKey: discord-webhook-url
    remoteRef:
      key: discord-webhook-url