apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: sonarr
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-vars
        image: ghcr.io/hotio/sonarr:release-4.0.17.2952
        name: sonarr
        ports:
        - containerPort: 8989
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz
          readOnly: true
        - mountPath: /config
          name: sonarr-vol
        - mountPath: /data
          name: data
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          tcpSocket:
            port: 8989
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 8989
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sonarr-nfs-pvc
      - hostPath:
          path: /etc/localtime
        name: tz
      - name: sonarr-vol
        persistentVolumeClaim:
          claimName: sonarr-pvc
