apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: qbittorrent
  annotations:
    keel.sh/policy: regex
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/match: '^release-.*-linux-amd64$'
    keel.sh/approvals: "1"
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: qbittorrent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: ghcr.io/hotio/qbittorrent:latest
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: env-vars
        ports:
        - containerPort: 8080
          name: web-ui
        - containerPort: 28601
          name: seeding
        volumeMounts:
        - mountPath: /data/torrents
          name: data
          subPath: torrents
        - mountPath: /etc/localtime
          name: tz
          readOnly: true
        - mountPath: /config
          name: qbittorrent-vol
        - mountPath: /config/data/BT_backup
          name: data
          subPath: BT_backup
        - mountPath: /config/wireguard
          name: writable-volume
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      initContainers:
      - name: copy-config
        image: busybox:latest
        command: ["sh", "-c", "cp /config-ro/wg0.conf /config-rw/"]
        volumeMounts:
        - mountPath: /config-ro
          name: vpn-config
        - mountPath: /config-rw
          name: writable-volume
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: qbittorrent-nfs-pvc
      - name: tz
        hostPath:
          path: /etc/localtime
      - name: qbittorrent-vol
        persistentVolumeClaim:
          claimName: qbittorrent-pvc
      - configMap:
          name: wg0.conf
        name: vpn-config
      - name: writable-volume
        emptyDir: {}



