apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      run: qbittorrent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: qbittorrent
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-vars
        image: ghcr.io/qbittorrent/docker-qbittorrent-nox:5.0.4-1
        name: qbittorrent
        ports:
        - containerPort: 8080
          name: web-ui
        - containerPort: 28601
          name: seeding
        volumeMounts:
        - mountPath: data/torrents
          name: data
          subPath: torrents
        - mountPath: /etc/localtime
          name: tz
          readOnly: true
        - mountPath: /config
          name: qbittorrent-vol
        - mountPath: /config/data/BT_backup
          name: data
          subPath: BT_backup
      volumes:
      - name: data
        nfs:
          path: /volume1/data
          server: 192.168.10.10
      - hostPath:
          path: /etc/localtime
        name: tz
      - name: qbittorrent-vol
        persistentVolumeClaim:
          claimName: qbittorrent-pvc
