apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      run: qbittorrent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: qbittorrent
    spec:
      containers:
      # - envFrom:
      #   - configMapRef:
      #       name: env-vars
      #   image: ghcr.io/qdm12/gluetun:v3.40.0
      #   imagePullPolicy: Always
      #   # https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/kubernetes.md
      #   lifecycle:
      #     postStart:
      #       exec:
      #         command: [ "/bin/sh", "-c", "(ip rule del table 51820; ip -6 rule del table 51820) || true" ]
      #   name: gluetun
      #   securityContext:
      #     capabilities:
      #       add: [ "NET_ADMIN" ]
      #   volumeMounts:
      #   - mountPath: /gluetun
      #     name: gluetun-config
      #  === qBittorrent container ===
      - envFrom:
        - configMapRef:
            name: env-vars
        image: hotio/qbittorrent:release-5.1.1
        name: qbittorrent
        ports:
        - containerPort: 8080
          name: web-ui
        - containerPort: 28601
          name: seeding
        volumeMounts:
        - mountPath: data/torrents
          name: data
          subPath: torrents
        - mountPath: /etc/localtime
          name: tz
          readOnly: true
        - mountPath: /config
          name: qbittorrent-vol
        - mountPath: /config/data/BT_backup
          name: data
          subPath: BT_backup
        - mountPath: /config/wireguard
          name: writable-volume
      initContainers:
      - command: [ "sh", "-c", "cp /config-ro/wg0.conf /config-rw/" ]
        image: busybox:latest
        name: copy-config
        volumeMounts:
        - mountPath: /config-ro
          name: vpn-config
        - mountPath: /config-rw
          name: writable-volume
      volumes:
      - name: data
        nfs:
          path: /mnt/volume1/data
          server: 192.168.10.16
      - hostPath:
          path: /etc/localtime
        name: tz
      - name: qbittorrent-vol
        persistentVolumeClaim:
          claimName: qbittorrent-pvc
      - configMap:
          name: wg0.conf
        name: vpn-config
      - emptyDir: {}
        name: writable-volume
      # - name: gluetun-config
      #   persistentVolumeClaim:
      #     claimName: gluetun-pvc
