configMapGenerator:
- envs:
  - env_vars.properties
  name: env-vars
- files:
  - wg0.conf
  name: wg0-blueprint
  options:
    disableNameSuffixHash: true
kind: Kustomization

namespace: qbittorrent

resources:
- deployment.yaml
- service.yaml
- storage.yaml
- nfs-pv-pvc.yaml
- qbittorrent-vpn-config.yaml
