configMapGenerator:
- envs:
  - env_vars.properties
  name: env-vars
- files:
  - wg0.conf
  name: wg0.conf
kind: Kustomization

namespace: qbittorrent

resources:
- deployment.yaml
- service.yaml
- storage.yaml
