configMapGenerator:
- envs:
  - env_vars.properties
  name: env-vars
- files:
  - qbitmanage-config.yaml
  name: qbitmanage-config

namespace: qbittorrent

resources:
- deployment.yaml
- service.yaml
- storage.yaml
