apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-vpn-config
  namespace: qbittorrent
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv-secret-store
  target:
    name: wg0-config-secret
    creationPolicy: Owner
  template:
    engineVersion: v2
    templateFrom:
    - configMap:
        name: wg0-blueprint
        items:
        - key: wg0.conf
  data:
  - secretKey: private_key
    remoteRef:
      key: proton-vpn-private-key