apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: qbittorrent # annotation name to combine the Service IP, make sure it's same name as in the service UDP yaml
    metallb.universe.tf/loadBalancerIPs: 192.168.10.201
  name: qbittorrent
  namespace: qbittorrent
spec:
  ports:
  - name: seeding
    port: 28601
    protocol: TCP
    targetPort: 28601
  - name: web-ui
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: qbittorrent
  type: LoadBalancer
