# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: gluetun-pv
# spec:
#   accessModes:
#   - ReadWriteOnce
#   capacity:
#     storage: 1Gi
#   csi:
#     driver: driver.longhorn.io
#     fsType: ext4
#     volumeHandle: gluetun
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: longhorn
#   volumeMode: Filesystem
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: gluetun-pvc
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: longhorn
#   volumeName: gluetun-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: qbittorrent
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: qbittorrent-pv
