[Interface]
# Key for k8s-qbit
# Bouncing = 7
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = $azurekv-secrets:proton-vpn-private-key
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-NJ#83
PublicKey = rPDCc4RoglCJ/M4BmFgr2eA8Ob7oc9qTTWG/79rApAI=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 163.5.171.56:51820

PersistentKeepalive = 25