apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb
spec:
  local:
    v4pools:
    - aggregation: /32
      pool: 192.168.10.210-192.168.10.255
      subnet: 192.168.10.0/24
