apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshelf
  namespace: bookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bookshelf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: bookshelf
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-vars
        image: ghcr.io/pennydreadful/bookshelf:softcover-v0.4.20.91
        name: bookshelf
        ports:
        - containerPort: 8787
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz
          readOnly: true
        - mountPath: /config
          name: bookshelf-vol
        - mountPath: /data
          name: data
      volumes:
      - name: data
        nfs:
          path: /mnt/volume1/data
          server: 192.168.10.16
      - hostPath:
          path: /etc/localtime
        name: tz
      - name: bookshelf-vol
        persistentVolumeClaim:
          claimName: bookshelf-pvc
