apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: overseerr
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1h"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: overseerr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: overseerr
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-vars
        image: ghcr.io/seerr-team/seerr:latest
        name: overseerr
        ports:
        - containerPort: 5055
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz
          readOnly: true
        - mountPath: /app/config
          name: overseerr-vol
        - mountPath: /data/media
          name: data
          subPath: media
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          tcpSocket:
            port: 5055
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 5055
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: overseerr-nfs-pvc
      - hostPath:
          path: /etc/localtime
        name: tz
      - name: overseerr-vol
        persistentVolumeClaim:
          claimName: overseerr-pvc
