# democratic-csi-iscsi/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-driver-config
  namespace: democratic-csi
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azurekv-secret-store
    kind: ClusterSecretStore
  target:
    name: democratic-csi-driver-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        driver-config-file.yaml: |
          driver: freenas-api-iscsi
          instance_id: ""
          httpConnection:
            protocol: https
            host: 192.168.10.16
            port: 443
            allowInsecure: true
            apiKey: "{{ .apiKey }}"
          zfs:
            datasetParentName: volume1/logs/vols
            detachedSnapshotsDatasetParentName: volume1/logs/snaps
            datasetEnableQuotas: true
            datasetEnableReservation: false
            datasetPermissionsMode: "0777"
            datasetPermissionsUser: 0
            datasetPermissionsGroup: 0
          iscsi:
            targetPortal: 192.168.10.16:3260
            namePrefix: csi-
            nameSuffix: "-clustera"
            targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 1
              targetGroupAuthType: None
            extentInsecureTpc: true
            extentXenCompat: false
            extentDisablePhysicalBlocksize: true
            extentBlocksize: 512
            extentRpm: "SSD"
            extentAvailThreshold: 0
  data:
  - secretKey: apiKey
    remoteRef:
      key: truenas-api-key
