apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bird
  namespace: router
spec:
  selector:
    matchLabels:
      app: bird
  template:
    metadata:
      labels:
        app: bird
    spec:
      containers:
      - env:
        - name: BIRD_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: BIRD_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: BIRD_ML_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.gitlab.com/purelb/bird_router:latest # Change the tag to the BIRD version you want to use.
        imagePullPolicy: Always
        name: bird
        resources:
          limits:
            cpu: 500m
            memory: 250Mi
          requests:
            cpu: 500m
            memory: 250Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: false
        volumeMounts:
        - mountPath: /usr/local/etc
          name: bird-cm
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      hostNetwork: true
      volumes:
      - configMap:
          name: bird-cm
        name: bird-cm


