
apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  ports:
  - name: web-ui
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: audiobookshelf
