notificationLevel: info
discord:
  enabled: true
basicauth:
  enabled: true
  user: admin
service:
  enabled: true
  type: ClusterIP
extraEnv:
  - name: BASIC_AUTH_PASSWORD
    # value: <path:azurekv-secrets#keel-password>
    value: "test"
  - name: DISCORD_WEBHOOK_URL
    value: <path:azurekv-secrets#discord-webhook-url>