notificationLevel: info
discord:
  enabled: true
basicauth:
  enabled: true
  user: admin
service:
  enabled: true
  type: ClusterIP
secret:
  create: false      
  name: azurekv-secrets
extraEnv:
  - name: BASIC_AUTH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: azurekv-secrets
        key: keel-password
  - name: DISCORD_WEBHOOK_URL
    valueFrom:
      secretKeyRef:
        name: azurekv-secrets
        key: discord-webhook-url