apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: plex
        image: ghcr.io/hotio/plex
        ports:
        - containerPort: 34200

