apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-server
  namespace: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      run: plexserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: plexserver
    spec:
      containers:
      - env:
        - name: PLEX_CLAIM_TOKEN
          value: <path:azurekv-secrets#plex-claim-token>
        - name: PLEX_ADVERTISE_URL
          value: http://192.168.10.200:32400
        - name: PLEX_NO_AUTH_NETWORKS
          value: ''
        - name: PLEX_BETA_INSTALL
          value: 'true'
        - name: NVIDIA_VISIBLE_DEVICES
          value: 'all'
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: 'compute,video,utility'
        image: ghcr.io/hotio/plex:release-1.41.9.9961-46083195d
        name: plex
        ports:
        - containerPort: 32400 #PMS
          name: plex
        - containerPort: 32400
          name: plex-udp
          protocol: UDP
        - containerPort: 32469 #Plex DLNA
          name: plex-dlna
        - containerPort: 5353
          name: plex-discovery
          protocol: UDP
        - containerPort: 1900 #Plex DLNA
          name: plex-dlna-udp
          protocol: UDP
        volumeMounts:
        - mountPath: data/media
          name: data
          subPath: media
        - mountPath: /etc/localtime
          name: tz
          readOnly: true
        - mountPath: /config
          name: plex-vol
        - mountPath: /dev/dri
          name: quicksync
      nodeName: spartan
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-nfs-pvc
      - hostPath:
          path: /etc/localtime
        name: tz
      - name: plex-vol
        persistentVolumeClaim:
          claimName: plex-pvc
      - hostPath:
          path: /dev/dri
        name: quicksync
