apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-server
  namespace: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      run: plexserver
  template:
    metadata:
      labels:
        run: plexserver
    spec:
      containers:
      - env:
        - name: PLEX_CLAIM
          value: claim-LZ-VG6Nyj1-mfwvydtPf # valid 4 minutes
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: compute,video,utility
        image: lscr.io/linuxserver/plex:1.41.0
        name: plex
        ports:
        - containerPort: 32400 #PMS
          name: plex
        - containerPort: 32400
          name: plex-udp
          protocol: UDP
        - containerPort: 32469 #Plex DLNA
          name: plex-dlna
        - containerPort: 5353
          name: plex-discovery
          protocol: UDP
        - containerPort: 1900 #Plex DLNA
          name: plex-dlna-udp
          protocol: UDP
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: data/media
          name: data
          subPath: media
        - mountPath: /etc/localtime
          name: tz
          readOnly: true
        - mountPath: /config
          name: plex-vol
      nodeName: spartan
      volumes:
      - name: data
        nfs:
          path: /volume1/data
          server: 192.168.10.10
      - hostPath:
          path: /etc/localtime
        name: tz
      - name: plex-vol
        persistentVolumeClaim:
          claimName: plex-pvc



