apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 25Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: plex-pv
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: longhorn
  volumeName: plex-pv
