apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 40Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: plex-pv
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: longhorn
  volumeName: plex-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Ti
  mountOptions:
  - vers=3
  - rsize=1048576
  - wsize=1048576
  - timeo=900
  - retrans=5
  nfs:
    path: /mnt/volume1/data
    readOnly: false
    server: 192.168.10.16
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-nfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
