apiVersion: v1
kind: Pod
metadata:
  name: satisfactory-migration
  namespace: satisfactory
spec:
  containers:
  - name: migrate
    image: alpine
    command: ["sh", "-c", "cp -a /source/. /dest/ && echo 'Migration complete'"]
    volumeMounts:
    - name: source-vol
      mountPath: /source
    - name: dest-vol
      mountPath: /dest
      subPath: satisfactory
  volumes:
  - name: source-vol
    persistentVolumeClaim:
      claimName: satisfactory-pvc # Longhorn PVC
  - name: dest-vol
    persistentVolumeClaim:
      claimName: satisfactory-nfs-pvc # NFS PVC
  restartPolicy: Never
