---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.10.205
  labels:
    app: satisfactory
  name: satisfactory
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - name: "api"
    port: 7777
    protocol: TCP
    targetPort: 7777
  - name: "game"
    port: 7777
    protocol: UDP
    targetPort: 7777
  - name: "messaging"
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: satisfactory
  type: LoadBalancer
