apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.10.203
  labels:
    app: satisfactory
  name: satisfactory
spec:
  ports:
  - name: game
    port: 7777
    protocol: UDP
    targetPort: 7777
  - name: gametcp
    port: 7777
    protocol: TCP
    targetPort: 7777
  selector:
    app: satisfactory
  type: LoadBalancer
