apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  name: argo-cd
  namespace: argocd # Apps need to be in the argocd namespace to appear in the UIspec:
  project: default
  source:
    path: argo-cd
    repoURL: https://github.com/mbernard/homelab.git
    targetRevision: HEAD
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
    - CreateNamespace=true
