apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azurekv
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://github.com/mbernard/homelab.git
    path: azurekv
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
