apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd
spec:
  destination:
    namespace: blackbox-exporter
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-blackbox-exporter
    targetRevision: 11.9.1
    helm:
      valueFiles:
      - $values/blackbox-exporter/values.yaml
  - ref: values
    repoURL: https://github.com/mbernard/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
