apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi-iscsi
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: https://democratic-csi.github.io/charts/
    chart: democratic-csi
    targetRevision: "*"
    helm:
      releaseName: democratic-csi-iscsi
      valueFiles:
      - $values/democratic-csi-iscsi/values.yaml
      parameters:
      - name: driver.config.httpConnection.apiKey
        value: $azurekv-secrets:truenas-api-key
  - ref: values
    repoURL: https://github.com/mbernard/homelab.git
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
