apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emissary
  namespace: argocd # Apps need to be in the argocd namespace to appear in the UI
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://github.com/mbernard/homelab.git
    path: emissary
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: emissary
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
