apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  name: external-secrets
  namespace: argocd # Apps need to be in the argocd namespace to appear in the UIspec:
  project: default  
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.20 # make sure to change this to the version you need 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
