apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-monitoring
  namespace: argocd # Apps need to be in the argocd namespace to appear in the UI
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  sources:
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      helm:
        valueFiles:
        - $values/grafana-monitoring/values.yaml
    # values from git
    - repoURL: https://github.com/mbernard/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana-monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true