apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mbernard/homelab.git
    targetRevision: HEAD
    path: keel  # folder containing Chart.yaml that wraps keel as a dependency
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: "-f values.yaml"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true