apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.keel.sh'
    chart: keel
    targetRevision: 1.2.0
    helm:
      values: |
        keel:
          ui:
            enabled: true
          notificationLevel: info
          discord:
            enabled: true
        env:
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: azurekv-secrets
              key: discord-webhook-url
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
