apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.keel.sh'
    chart: keel
    targetRevision: 1.2.0
    helm:
      values: |
        notificationLevel: info
        discord:
          enabled: true
          webhookUrl: <path:azurekv-secrets#discord-webhook-url>
        basicauth:
          enabled: true
          user: admin
          password: <path:azurekv-secrets#keel-password>
        service:
          enabled: true
          type: ClusterIP
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
