apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: oci://ghcr.io/grafana-community/helm-charts
    chart: loki
    targetRevision: 9.5.0
    helm:
      valuesFiles:
      - $values/loki/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
