apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-problem-detector
  namespace: argocd
spec:
  destination:
    namespace: node-problem-detector
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: oci://ghcr.io/deliveryhero/helm-charts/node-problem-detector
    chart: node-problem-detector
    targetRevision: 2.4.0
    helm:
      valueFiles:
      - $values/node-problem-detector/values.yaml
  - ref: values
    repoURL: https://github.com/mbernard/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
