apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  name: notifiarr
  namespace: argocd # Apps need to be in the argocd namespace to appear in the UI
spec:
  destination:
    namespace: notifiarr
    server: https://kubernetes.default.svc
  project: default
  source:
    path: notifiarr
    repoURL: https://github.com/mbernard/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
