apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  name: nvidia
  namespace: argocd # Apps need to be in the argocd namespace to appear in the UI
spec:
  destination:
    namespace: nvidia
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: nvidia-device-plugin
    repoURL: https://nvidia.github.io/k8s-device-plugin
    targetRevision: 0.16.2
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
