apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  name: technitium
  namespace: argocd
spec:
  destination:
    namespace: technitium
    server: https://kubernetes.default.svc
  project: default
  source:
    path: technitium
    repoURL: https://github.com/mbernard/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
