apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  destination:
    namespace: tempo
    server: https://kubernetes.default.svc
  project: default
  sources:
  # 1. Define the Git repo FIRST so 'ref: values' is available
  - repoURL: https://github.com/mbernard/homelab.git
    targetRevision: HEAD
    ref: values

  # 2. Reference the chart SECOND
  - repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 0.16.9
    helm:
      valuesFiles:
      # This now points directly to the 'ref' defined above
      - $values/tempo/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
