apiVersion: v1
kind: PersistentVolume
metadata:
  name: unpackerr-nfs-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/volume1/data
    server: 192.168.10.16
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unpackerr-nfs-pvc
  namespace: unpackerr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Ti
  volumeName: unpackerr-nfs-pv
