cluster:
  name: homelab
externalServices:
  prometheus:
    host: https://prometheus-prod-32-prod-ca-east-0.grafana.net
    basicAuth:
      username: "1733573"
      password: glc_eyJvIjoiMTE5NDA1MiIsIm4iOiJzdGFjay0xMDA4NzM2LWludGVncmF0aW9uLWhvbWVsYWItaG9tZWxhYiIsImsiOiJZYTZaZzg0bzYyb0wyY2QxMDFuMGdqYlEiLCJtIjp7InIiOiJwcm9kLWNhLWVhc3QtMCJ9fQ==
  loki:
    host: https://logs-prod-018.grafana.net
    basicAuth:
      username: "966516"
      password: glc_eyJvIjoiMTE5NDA1MiIsIm4iOiJzdGFjay0xMDA4NzM2LWludGVncmF0aW9uLWhvbWVsYWItaG9tZWxhYiIsImsiOiJZYTZaZzg0bzYyb0wyY2QxMDFuMGdqYlEiLCJtIjp7InIiOiJwcm9kLWNhLWVhc3QtMCJ9fQ==
  tempo:
    host: https://tempo-prod-13-prod-ca-east-0.grafana.net:443
    basicAuth:
      username: "960831"
      password: glc_eyJvIjoiMTE5NDA1MiIsIm4iOiJzdGFjay0xMDA4NzM2LWludGVncmF0aW9uLWhvbWVsYWItaG9tZWxhYiIsImsiOiJZYTZaZzg0bzYyb0wyY2QxMDFuMGdqYlEiLCJtIjp7InIiOiJwcm9kLWNhLWVhc3QtMCJ9fQ==
metrics:
  enabled: true
  alloy:
    metricsTuning:
      useIntegrationAllowList: true
  cost:
    enabled: true
  kepler:
    enabled: true
  node-exporter:
    enabled: true
logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true
traces:
  enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: true
  grafanaCloudMetrics:
    enabled: false
opencost:
  enabled: true
  opencost:
    exporter:
      defaultClusterId: homelab
    prometheus:
      external:
        url: https://prometheus-prod-32-prod-ca-east-0.grafana.net/api/prom
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-operator-crds:
  enabled: true
kepler:
  enabled: true
  # Luna's CPU doesn't support the lib Kepler uses to collect metrics
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - luna
alloy: {}
alloy-events: {}
alloy-logs: {}