apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole-ro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pihole
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - env:
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              key: azurekv-secrets
              name: pihole-admin-password
        envFrom:
        - configMapRef:
            name: env-vars
        image: pihole/pihole:2024.01.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 30
          tcpSocket:
            port: dns-tcp
        name: pihole-ro
        ports:
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        readinessProbe:
          exec:
            command: ['dig', '@127.0.0.1', 'cloudflare.com']
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 20
        resources:
          limits:
            cpu: "250m"
            memory: "896Mi"
          requests:
            cpu: "20m"
            memory: "512Mi"
        volumeMounts:
        - mountPath: /etc/pihole
          name: pihole-etc
          readOnly: true
        - mountPath: /etc/dnsmasq.d
          name: pihole-dnsm
          readOnly: true
      volumes:
      - name: pihole-etc
        persistentVolumeClaim:
          claimName: pihole-etc-pvc
      - name: pihole-dnsm
        persistentVolumeClaim:
          claimName: pihole-dnsm-pvc
