apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- envs:
  - env_vars.properties
  name: env-vars
kind: Kustomization

namespace: pihole

resources:
- statefulset.yaml
- service.yaml
- storage-dnsm.yaml
- storage-etc.yaml

