apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
    metallb.universe.tf/loadBalancerIPs: 192.168.10.202
  name: pihole-udp
spec:
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ports:
  - name: dnsudp
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    app: pihole
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
    metallb.universe.tf/loadBalancerIPs: 192.168.10.202
  name: pihole-tcp
spec:
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ports:
  - name: dnstcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    app: pihole
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
spec:
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    statefulset.kubernetes.io/pod-name: pihole-0
  type: ClusterIP
