apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: pihole
  name: pihole
  namespace: pihole
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - pihole
            topologyKey: "kubernetes.io/hostname"
      containers:
      - env:
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              key: pihole-admin-password
              name: azurekv-secrets
        envFrom:
        - configMapRef:
            name: env-vars
        image: pihole/pihole:2025.11.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 30
          tcpSocket:
            port: dns-tcp
        name: pihole-rw
        ports:
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 80
          name: web
          protocol: TCP
        readinessProbe:
          exec:
            command: ['dig', '@127.0.0.1', 'cloudflare.com']
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 20
        volumeMounts:
        - mountPath: /etc/pihole
          name: etc-pvc
        - mountPath: /etc/dnsmasq.d
          name: dnsm-pvc
  volumeClaimTemplates:
  - metadata:
      name: etc-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: dnsm-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
