apiVersion: v1
kind: PersistentVolume
metadata:
  name: dnsm-pv-pihole-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: dnsm-pihole-0
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # <claim template name>-<stateful set name>-<stateful set number>
  name: dnsm-pvc-pihole-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: dnsm-pv-pihole-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dnsm-pv-pihole-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: dnsm-pihole-1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # <claim template name>-<stateful set name>-<stateful set number>
  name: dnsm-pvc-pihole-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: dnsm-pv-pihole-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dnsm-pv-pihole-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: dnsm-pihole-2
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # <claim template name>-<stateful set name>-<stateful set number>
  name: dnsm-pvc-pihole-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: dnsm-pv-pihole-2
