apiVersion: v1
kind: PersistentVolume
metadata:
  name: etc-pv-pihole-0
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: etc-pihole-0
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # <claim template name>-<stateful set name>-<stateful set number>
  name: etc-pvc-pihole-0
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: etc-pv-pihole-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etc-pv-pihole-1
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: etc-pihole-1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # <claim template name>-<stateful set name>-<stateful set number>
  name: etc-pvc-pihole-1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: etc-pv-pihole-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etc-pv-pihole-2
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: etc-pihole-2
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # <claim template name>-<stateful set name>-<stateful set number>
  name: etc-pvc-pihole-2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: etc-pv-pihole-2
