csiDriver:
  name: "org.democratic-csi.iscsi"

storageClasses:
- name: truenas-iscsi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: ext4

driver:
  existingConfigSecret: democratic-csi-driver-config
