apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: technitium
  name: technitium
  namespace: technitium
spec:
  replicas: 3
  selector:
    matchLabels:
      app: technitium
  serviceName: technitium-headless # Required for StatefulSets
  template:
    metadata:
      labels:
        app: technitium
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - technitium
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: technitium/dns-server:15.2.0
        imagePullPolicy: IfNotPresent
        name: technitium
        ports:
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 5380
          name: web
          protocol: TCP
        - containerPort: 53443
          name: cluster
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/dns
          name: etc-pvc
        # Use subPath to inject the file natively inside the /etc/dns directory
        - name: secrets-volume
          mountPath: /etc/dns/technitium.pfx
          subPath: technitium-pfx
          readOnly: true
        # This injects your self-signed cert into the OS trusted anchors dynamically
        - mountPath: /etc/ssl/certs/technitium-ca.pem
          name: secrets-volume
          subPath: technitium-chain-pem
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          tcpSocket:
            port: 5380
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 5380
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: secrets-volume
        secret:
          secretName: azurekv-secrets
          items:
          - key: technitium-pfx
            path: technitium-pfx
          - key: technitium-chain-pem
            path: technitium-chain-pem
  volumeClaimTemplates:
  - metadata:
      name: etc-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi