apiVersion: apps/v1
kind: Deployment
metadata:
  name: recyclarr
  namespace: recyclarr
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: recyclarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: recyclarr
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-vars
        image: ghcr.io/recyclarr/recyclarr:latest
        name: recyclarr
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz
          readOnly: true
        - mountPath: /config
          name: recyclarr-vol
        - mountPath: /config/recyclarr.yml
          name: recyclarr-config
          subPath: recyclarr.yml
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
      volumes:
      - hostPath:
          path: /etc/localtime
        name: tz
      - name: recyclarr-vol
        persistentVolumeClaim:
          claimName: recyclarr-pvc
      - configMap:
          name: recyclarr-config
        name: recyclarr-config
