apiVersion: apps/v1
kind: Deployment
metadata:
  name: omegabrr
  namespace: omegabrr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: omegabrr
  template:
    metadata:
      labels:
        run: omegabrr
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-vars
        image: ghcr.io/autobrr/omegabrr:v1.14
        name: omegabrr
        ports:
        - containerPort: 7441
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz
          readOnly: true
        - mountPath: /config
          name: omegabrr-config
      volumes:
      - hostPath:
          path: /etc/localtime
        name: tz
      - configMap:
          name: omegabrr-config
        name: omegabrr-config

