configMapGenerator:
- envs:
  - env_vars.properties
  name: env-vars
- files:
  - config.yaml
  name: omegabrr-config
generatorOptions:
  labels:
    app.kubernetes.io/part-of: argocd

namespace: omegabrr

resources:
- deployment.yaml
- service.yaml
