apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-nfs-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/volume1/data
    server: 192.168.10.16
  mountOptions:
  - vers=3
  - rsize=1048576
  - wsize=1048576
  - timeo=900
  - retrans=5
  - noatime
  - nodiratime
  - hard
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-nfs-pvc
  namespace: calibre
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: "nfs"
  resources:
    requests:
      storage: 10Ti
  volumeName: calibre-nfs-pv
