
apiVersion: v1
kind: Service
metadata:
  name: calibre
  namespace: calibre
spec:
  ports:
  - name: desktop-gui
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: webserver
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    run: calibre
