# based on https://developers.cloudflare.com/cloudflare-one/tutorials/many-cfd-one-tunnel/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1h"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        # 1. Override the entrypoint to use a shell
        command: ["/bin/sh", "-c"]
        # 2. Decode the variable and pass it inline to the run command
        args:
        - |
          CLEAN_TOKEN=$(echo -n "$RAW_KV_TOKEN" | base64)
          exec cloudflared tunnel --no-autoupdate run --token "$CLEAN_TOKEN"
        image: cloudflare/cloudflared:latest
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /ready
            port: 2000
          initialDelaySeconds: 60
          periodSeconds: 10
        env:
        - name: RAW_KV_TOKEN
          valueFrom:
            secretKeyRef:
              key: cloudflare-tunnel-token
              name: azurekv-secrets
        volumeMounts:
        - mountPath: /etc/cloudflared/config
          name: config
          readOnly: true
        - mountPath: /etc/cloudflared/creds
          name: creds
          readOnly: true
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
      volumes:
      - name: creds
        secret:
          secretName: azurekv-secrets
      - configMap:
          items:
          - key: config.yaml
            path: config.yaml
          name: cloudflared
        name: config
