apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared

# https://developers.cloudflare.com/cloudflare-one/tutorials/many-cfd-one-tunnel/
resources:
- https://raw.githubusercontent.com/cloudflare/argo-tunnel-examples/master/named-tunnel-k8s/cloudflared.yaml

patches:
- path: deployment.yaml

configMapGenerator:
- name: cloudflared
  behavior: merge
  files:
    - config.yaml