apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - config.yaml
  name: cloudflared
kind: Kustomization

# https://developers.cloudflare.com/cloudflare-one/tutorials/many-cfd-one-tunnel/
namespace: cloudflared
resources:
- deployment.yaml
