apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared

# https://developers.cloudflare.com/cloudflare-one/tutorials/many-cfd-one-tunnel/
resources:
- deployment.yaml

configMapGenerator:
- name: cloudflared
  files:
    - config.yaml