
apiVersion: v1
kind: Service
metadata:
  name: readarr-audio
  namespace: readarr-audio
spec:
  ports:
  - name: web-ui
    port: 80
    protocol: TCP
    targetPort: 8787
  selector:
    run: readarr-audio
