apiVersion: apps/v1
kind: Deployment
metadata:
  name: cross-seed
  namespace: cross-seed
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cross-seed
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: cross-seed
    spec:
      containers:
      - command:
        - 'cross-seed'
        - 'daemon'
        envFrom:
        - configMapRef:
            name: env-vars
        image: ghcr.io/cross-seed/cross-seed:6.10.1
        name: cross-seed
        ports:
        - containerPort: 2468
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz
          readOnly: true
        - mountPath: /config
          name: cross-seed-vol
        - mountPath: /data
          name: data
        - mountPath: /torrents
          name: data
          readOnly: true
          subPath: BT_backup
        - mountPath: /config/config.js
          name: cross-seed-config
          subPath: config.js
      volumes:
      - name: data
        nfs:
          path: /volume1/data
          server: 192.168.10.10
      - hostPath:
          path: /etc/localtime
        name: tz
      - name: cross-seed-vol
        persistentVolumeClaim:
          claimName: cross-seed-pvc
      - configMap:
          name: cross-seed-config
        name: cross-seed-config
