apiVersion: apps/v1
kind: Deployment
metadata:
  name: cross-seed
  namespace: cross-seed
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cross-seed
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: cross-seed
    spec:
      containers:
      - command:
        - 'cross-seed'
        - 'daemon'
        envFrom:
        - configMapRef:
            name: env-vars
        image: ghcr.io/cross-seed/cross-seed:7.0.0-13
        name: cross-seed
        ports:
        - containerPort: 2468
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz
          readOnly: true
        - mountPath: /config
          name: cross-seed-vol
        - mountPath: /data
          name: data
        - mountPath: /torrents
          name: data
          readOnly: true
          subPath: BT_backup
        - mountPath: /config/config.js
          name: cross-seed-config
          subPath: config.js
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        securityContext:
          capabilities:
            drop:
            - ALL
        livenessProbe:
          tcpSocket:
            port: 2468
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 2468
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: cross-seed-nfs-pvc
      - hostPath:
          path: /etc/localtime
        name: tz
      - name: cross-seed-vol
        persistentVolumeClaim:
          claimName: cross-seed-pvc
      - configMap:
          name: cross-seed-config
        name: cross-seed-config
