kind: Kustomization

namespace: cross-seed

configMapGenerator:
- envs:
  - env_vars.properties
  name: env-vars
- files:
  - config.js
  name: cross-seed-config

resources:
- deployment.yaml
- service.yaml
- storage.yaml
- nfs-pv-pvc.yaml
