configMapGenerator:
- envs:
  - env_vars.properties
  name: env-vars
- files:
  - config.js
  name: cross-seed-config

namespace: qbittorrent

resources:
- deployment.yaml
- service.yaml
- storage.yaml
