apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azurekv-secret-store
spec:
  provider:
    azurekv:
      environmentType: PublicCloud
      authType: ServicePrincipal
      vaultUrl: "https://mig-homelab-kv.vault.azure.net"
      tenantId: 516d9acc-a413-4bb7-8275-a07bd784e364
      authSecretRef:
        clientId:
          name: azure-homelab-cred
          key: client-id
          namespace: azurekv
        clientSecret:
          name: azure-homelab-cred
          key: client-secret
          namespace: azurekv
