apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: emissary

helmCharts:
  - name: emissary-ingress
    repo: https://app.getambassador.io
    releaseName: emissary-ingress
    namespace: emissary
