apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshelf-audio
  namespace: bookshelf-audio
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bookshelf-audio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: bookshelf-audio
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-vars
        image: ghcr.io/pennydreadful/bookshelf:softcover
        name: bookshelf-audio
        ports:
        - containerPort: 8787
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz
          readOnly: true
        - mountPath: /config
          name: bookshelf-audio-vol
        - mountPath: /data
          name: data
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 8787
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 8787
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: bookshelf-audio-nfs-pvc
      - hostPath:
          path: /etc/localtime
        name: tz
      - name: bookshelf-audio-vol
        persistentVolumeClaim:
          claimName: bookshelf-audio-pvc
