apiVersion: v1
data:
  policy.csv: |
    p, role:myrole, exec, create, */*, allow
    g, mig@miguelbernard.com, role:admin
  policy.default: role:readonly
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm