apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

patches:
- path: argocd-cm.yaml 
- path: argocd-rbac-cm.yaml
- path: argocd-server.yaml
- path: clusterrole.yaml

# https://github.com/argoproj/argo-cd/tree/master/manifests/ha
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml
- repo.yaml
