apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
# https://github.com/argoproj/argo-cd/tree/master/manifests/ha
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml
- azure-keyvault-cred
- ../overlays/cmp-sidecar
