apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml

# agrocd vault plugin https://github.com/argoproj-labs/argocd-vault-plugin/blob/main/manifests/cmp-sidecar/cmp-plugin.yaml
- https://raw.githubusercontent.com/argoproj-labs/argocd-vault-plugin/main/manifests/cmp-sidecar/cmp-plugin.yaml

patchesStrategicMerge:
- https://raw.githubusercontent.com/argoproj-labs/argocd-vault-plugin/main/manifests/cmp-sidecar/argocd-repo-server.yaml
