# Git repositories configure Argo CD with (optional).
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/secret-type: repository
  name: homelab
  namespace: argocd
stringData:
  password: $azurekv-secrets:github-personal-access-token-argocd
  url: https://github.com/mbernard/homelab #aHR0cHM6Ly9naXRodWIuY29tL21iZXJuYXJkL2hvbWVsYWI=
  username: mbernard # bWJlcm5hcmQ=
