# Git repositories configure Argo CD with (optional).
apiVersion: v1
data:
  password: $azurekv-secrets:github-personal-access-token-argocd
  url: aHR0cHM6Ly9naXRodWIuY29tL21iZXJuYXJkL2hvbWVsYWI= # https://github.com/mbernard/homelab
  username: bWJlcm5hcmQ= # mbernard
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: homelab
  namespace: argocd