apiVersion: apps/v1
kind: Deployment
metadata:
  name: autobrr
  namespace: autobrr
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
    keel.sh/pollSchedule: "@every 1h"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: autobrr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: autobrr
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-vars
        image: ghcr.io/autobrr/autobrr:latest
        imagePullPolicy: Always
        name: autobrr
        ports:
        - containerPort: 7474
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz
          readOnly: true
        - mountPath: /config
          name: autobrr-vol
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 7474
          initialDelaySeconds: 300
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 7474
          initialDelaySeconds: 300
          periodSeconds: 10
      volumes:
      - hostPath:
          path: /etc/localtime
        name: tz
      - name: autobrr-vol
        persistentVolumeClaim:
          claimName: autobrr-pvc
