apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argocd-vault-plugin-helm
spec:
  allowConcurrency: true

  # Optimized discovery to cleanly detect any Helm chart source
  discover:
    find:
      command:
      - sh
      - "-c"
      - "find . -name 'Chart.yaml'"
      
  generate:
    command:
    - sh
    - "-c"
    - |
      # Under multiple sources, Argo CD automatically populates $ARGOCD_APP_SOURCE_<ref>
      # as environment variables inside this sidecar container environment.
      helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . --include-crds |
      argocd-vault-plugin generate -
  lockRepo: false