apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argocd-vault-plugin
spec:
  allowConcurrency: true
  discover:
    find:
      command:
      - sh
      - "-c"
      - "if [ ! -f kustomization.yaml ] && [ ! -f Chart.yaml ]; then find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep .; else false; fi"
  generate:
    command:
    - argocd-vault-plugin
    - generate
    - "."
  lockRepo: false
