apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot
  namespace: longhorn
spec:
  concurrency: 2
  cron: "0 * * * *" # every hour
  groups:
  - default # Having default in groups will automatically schedule this recurring job to any volume with no recurring job.
  retain: 24
  task: "snapshot"
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup
  namespace: longhorn
spec:
  concurrency: 2
  cron: "0 0 * * *" # every day
  groups:
  - default # Having default in groups will automatically schedule this recurring job to any volume with no recurring job.
  retain: 7
  task: "backup"
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: filesystem-trim
  namespace: longhorn
spec:
  concurrency: 2
  cron: "0 0 * * *" # every day
  groups:
  - default # Having default in groups will automatically schedule this recurring job to any volume with no recurring job.
  retain: 7
  task: "filesystem-trim"
