apiVersion: apps/v1
kind: Deployment
metadata:
  name: stash-server
  namespace: stash
spec:
  selector:
    matchLabels:
      run: stash
  replicas: 1
  template:
    metadata:
      labels:
        run: stash
    spec:
      containers:
        - image: stashapp/stash
          name: stash
          ports:
            - containerPort: 9999
          env:
            - name: STASH_STASH
              value: /data/
            - name: STASH_GENERATED
              value: /generated/
            - name: STASH_METADATA
              value: /metadata/
            - name: STASH_CACHE
              value: /cache/
            - name: STASH_PORT
              value: '9999'
          volumeMounts:
            ## Point this at your collection.
            - name: nfs-porn
              mountPath: /data
            - name: tz
              mountPath: /etc/localtime
              readOnly: true
            ## Keep configs, scrapers, and plugins here.
            - name: stash-vol
              subPath: root
              mountPath: /root/.stash
            ## This is where your stash's metadata lives
            - name: stash-vol
              subPath: metadata
              mountPath: /metadata
            ## Any other cache content.
            - name: stash-vol
              subPath: cache
              mountPath: /cache
            ## Where to store binary blob data (scene covers, images)
            - name: stash-vol
              subPath: blobs
              mountPath: /blobs
            ## Where to store generated content (screenshots,previews,transcodes,sprites)
            - name: stash-vol
              subPath: generated
              mountPath: /generated
      volumes:
        - name: nfs-porn
          nfs:
            server: 192.168.10.10
            path: /volume1/private/Porn
        - name: tz
          hostPath:
            path: /etc/localtime
        - name: stash-vol
          persistentVolumeClaim:
            claimName: stash-pvc
