apiVersion: apps/v1
kind: Deployment
metadata:
  name: stash-server
  namespace: stash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stash
    spec:
      containers:
      - image: stashapp/stash
        name: stash
      #   volumeMounts:
      #   - mountPath: /etc/cloudflared/config
      #     name: config
      #     readOnly: true
      #   - mountPath: /etc/cloudflared/creds
      #     name: creds
      #     readOnly: true
      # volumes:
      # - name: creds
      #   secret:
      #     secretName: azurekv-secrets
      # - configMap:
      #     items:
      #     - key: config.yaml
      #       path: config.yaml
      #     name: cloudflared
      #   name: config