kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: stash-sc
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  dataLocality: "best-effort"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: stash-sc
  resources:
    requests:
      storage: 10Gi